/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface FadeIn {
    'delay'?: string;
    'down'?: boolean;
    'left'?: boolean;
    'offsetPx'?: number;
    'offsetVh'?: number;
    'revert'?: boolean;
    'right'?: boolean;
    'up'?: boolean;
    'withScroll'?: boolean;
  }
  interface FancyName {
    'url'?: string;
  }
  interface PageAbout {}
  interface PageHome {}
  interface PageNotfound {}
  interface PageProjects {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLFadeInElement extends Components.FadeIn, HTMLStencilElement {}
  var HTMLFadeInElement: {
    prototype: HTMLFadeInElement;
    new (): HTMLFadeInElement;
  };

  interface HTMLFancyNameElement extends Components.FancyName, HTMLStencilElement {}
  var HTMLFancyNameElement: {
    prototype: HTMLFancyNameElement;
    new (): HTMLFancyNameElement;
  };

  interface HTMLPageAboutElement extends Components.PageAbout, HTMLStencilElement {}
  var HTMLPageAboutElement: {
    prototype: HTMLPageAboutElement;
    new (): HTMLPageAboutElement;
  };

  interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {}
  var HTMLPageHomeElement: {
    prototype: HTMLPageHomeElement;
    new (): HTMLPageHomeElement;
  };

  interface HTMLPageNotfoundElement extends Components.PageNotfound, HTMLStencilElement {}
  var HTMLPageNotfoundElement: {
    prototype: HTMLPageNotfoundElement;
    new (): HTMLPageNotfoundElement;
  };

  interface HTMLPageProjectsElement extends Components.PageProjects, HTMLStencilElement {}
  var HTMLPageProjectsElement: {
    prototype: HTMLPageProjectsElement;
    new (): HTMLPageProjectsElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'fade-in': HTMLFadeInElement;
    'fancy-name': HTMLFancyNameElement;
    'page-about': HTMLPageAboutElement;
    'page-home': HTMLPageHomeElement;
    'page-notfound': HTMLPageNotfoundElement;
    'page-projects': HTMLPageProjectsElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface FadeIn {
    'delay'?: string;
    'down'?: boolean;
    'left'?: boolean;
    'offsetPx'?: number;
    'offsetVh'?: number;
    'revert'?: boolean;
    'right'?: boolean;
    'up'?: boolean;
    'withScroll'?: boolean;
  }
  interface FancyName {
    'url'?: string;
  }
  interface PageAbout {}
  interface PageHome {}
  interface PageNotfound {}
  interface PageProjects {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'fade-in': FadeIn;
    'fancy-name': FancyName;
    'page-about': PageAbout;
    'page-home': PageHome;
    'page-notfound': PageNotfound;
    'page-projects': PageProjects;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'fade-in': LocalJSX.FadeIn & JSXBase.HTMLAttributes<HTMLFadeInElement>;
      'fancy-name': LocalJSX.FancyName & JSXBase.HTMLAttributes<HTMLFancyNameElement>;
      'page-about': LocalJSX.PageAbout & JSXBase.HTMLAttributes<HTMLPageAboutElement>;
      'page-home': LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
      'page-notfound': LocalJSX.PageNotfound & JSXBase.HTMLAttributes<HTMLPageNotfoundElement>;
      'page-projects': LocalJSX.PageProjects & JSXBase.HTMLAttributes<HTMLPageProjectsElement>;
    }
  }
}


