/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface BlogList {
    }
    interface BlogSingle {
        "match": any;
    }
    interface FadeIn {
        "delay"?: string;
        "down"?: boolean;
        "left"?: boolean;
        "offsetPx"?: number;
        "offsetVh"?: number;
        "revert"?: boolean;
        "right"?: boolean;
        "up"?: boolean;
        "withScroll"?: boolean;
    }
    interface FancyName {
        "url"?: string;
    }
    interface MainBg {
    }
    interface PageAbout {
    }
    interface PageHome {
    }
    interface PageLoading {
    }
    interface PageNotfound {
    }
    interface PageProjects {
    }
    interface PageTitle {
        "heroImage"?: string;
    }
    interface SeoTags {
        "description": string;
        "image": string;
        "pageTitle": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLBlogListElement extends Components.BlogList, HTMLStencilElement {
    }
    var HTMLBlogListElement: {
        prototype: HTMLBlogListElement;
        new (): HTMLBlogListElement;
    };
    interface HTMLBlogSingleElement extends Components.BlogSingle, HTMLStencilElement {
    }
    var HTMLBlogSingleElement: {
        prototype: HTMLBlogSingleElement;
        new (): HTMLBlogSingleElement;
    };
    interface HTMLFadeInElement extends Components.FadeIn, HTMLStencilElement {
    }
    var HTMLFadeInElement: {
        prototype: HTMLFadeInElement;
        new (): HTMLFadeInElement;
    };
    interface HTMLFancyNameElement extends Components.FancyName, HTMLStencilElement {
    }
    var HTMLFancyNameElement: {
        prototype: HTMLFancyNameElement;
        new (): HTMLFancyNameElement;
    };
    interface HTMLMainBgElement extends Components.MainBg, HTMLStencilElement {
    }
    var HTMLMainBgElement: {
        prototype: HTMLMainBgElement;
        new (): HTMLMainBgElement;
    };
    interface HTMLPageAboutElement extends Components.PageAbout, HTMLStencilElement {
    }
    var HTMLPageAboutElement: {
        prototype: HTMLPageAboutElement;
        new (): HTMLPageAboutElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageLoadingElement extends Components.PageLoading, HTMLStencilElement {
    }
    var HTMLPageLoadingElement: {
        prototype: HTMLPageLoadingElement;
        new (): HTMLPageLoadingElement;
    };
    interface HTMLPageNotfoundElement extends Components.PageNotfound, HTMLStencilElement {
    }
    var HTMLPageNotfoundElement: {
        prototype: HTMLPageNotfoundElement;
        new (): HTMLPageNotfoundElement;
    };
    interface HTMLPageProjectsElement extends Components.PageProjects, HTMLStencilElement {
    }
    var HTMLPageProjectsElement: {
        prototype: HTMLPageProjectsElement;
        new (): HTMLPageProjectsElement;
    };
    interface HTMLPageTitleElement extends Components.PageTitle, HTMLStencilElement {
    }
    var HTMLPageTitleElement: {
        prototype: HTMLPageTitleElement;
        new (): HTMLPageTitleElement;
    };
    interface HTMLSeoTagsElement extends Components.SeoTags, HTMLStencilElement {
    }
    var HTMLSeoTagsElement: {
        prototype: HTMLSeoTagsElement;
        new (): HTMLSeoTagsElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "blog-list": HTMLBlogListElement;
        "blog-single": HTMLBlogSingleElement;
        "fade-in": HTMLFadeInElement;
        "fancy-name": HTMLFancyNameElement;
        "main-bg": HTMLMainBgElement;
        "page-about": HTMLPageAboutElement;
        "page-home": HTMLPageHomeElement;
        "page-loading": HTMLPageLoadingElement;
        "page-notfound": HTMLPageNotfoundElement;
        "page-projects": HTMLPageProjectsElement;
        "page-title": HTMLPageTitleElement;
        "seo-tags": HTMLSeoTagsElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface BlogList {
    }
    interface BlogSingle {
        "match"?: any;
    }
    interface FadeIn {
        "delay"?: string;
        "down"?: boolean;
        "left"?: boolean;
        "offsetPx"?: number;
        "offsetVh"?: number;
        "revert"?: boolean;
        "right"?: boolean;
        "up"?: boolean;
        "withScroll"?: boolean;
    }
    interface FancyName {
        "url"?: string;
    }
    interface MainBg {
    }
    interface PageAbout {
    }
    interface PageHome {
    }
    interface PageLoading {
    }
    interface PageNotfound {
    }
    interface PageProjects {
    }
    interface PageTitle {
        "heroImage"?: string;
    }
    interface SeoTags {
        "description"?: string;
        "image"?: string;
        "pageTitle"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "blog-list": BlogList;
        "blog-single": BlogSingle;
        "fade-in": FadeIn;
        "fancy-name": FancyName;
        "main-bg": MainBg;
        "page-about": PageAbout;
        "page-home": PageHome;
        "page-loading": PageLoading;
        "page-notfound": PageNotfound;
        "page-projects": PageProjects;
        "page-title": PageTitle;
        "seo-tags": SeoTags;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "blog-list": LocalJSX.BlogList & JSXBase.HTMLAttributes<HTMLBlogListElement>;
            "blog-single": LocalJSX.BlogSingle & JSXBase.HTMLAttributes<HTMLBlogSingleElement>;
            "fade-in": LocalJSX.FadeIn & JSXBase.HTMLAttributes<HTMLFadeInElement>;
            "fancy-name": LocalJSX.FancyName & JSXBase.HTMLAttributes<HTMLFancyNameElement>;
            "main-bg": LocalJSX.MainBg & JSXBase.HTMLAttributes<HTMLMainBgElement>;
            "page-about": LocalJSX.PageAbout & JSXBase.HTMLAttributes<HTMLPageAboutElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-loading": LocalJSX.PageLoading & JSXBase.HTMLAttributes<HTMLPageLoadingElement>;
            "page-notfound": LocalJSX.PageNotfound & JSXBase.HTMLAttributes<HTMLPageNotfoundElement>;
            "page-projects": LocalJSX.PageProjects & JSXBase.HTMLAttributes<HTMLPageProjectsElement>;
            "page-title": LocalJSX.PageTitle & JSXBase.HTMLAttributes<HTMLPageTitleElement>;
            "seo-tags": LocalJSX.SeoTags & JSXBase.HTMLAttributes<HTMLSeoTagsElement>;
        }
    }
}
